# Target resored root (*SortEvent*.root) files.
target_files:
  - sacla_analysis-resorted.root

# MongoDB collection where analyzed Hits will be saved. Not supported yet.
save_to: mongodb://<addr>/<db>.<collection>

# Parameters of SACLA momentum models (momentum analyzer). Hit (t, x, y)
# will be calibrated to...
#   (t) -> (t - t0),
#   (x, y) -> (((x, y) * rot(th) - (x0, y0)) * (dx, dy)) + (x1, y1).
momentum_analyzer:
  t0: 626.6  # A calibration factor. Default: 0.
  th: 0  # A calibration factor. Default: 0.
  x0: 0  # A calibration factor. Default: 0.
  y0: 0  # A calibration factor. Default: 0.
  dx: 1  # A calibration factor. Default: 1.
  dy: 1  # A calibration factor. Default: 1.
  models:  # SACLA momentum models.
    particle_a:
      # Mass of the model particle. This parameter will be used to
      # calculate kinetic energy from three-dimensional momentum...
      #   (px, py, pz) -> (px**2 + py**2 + pz**2) / 2 / mass.
      # This program does not consider units. You may want to
      # convert the unit of kinetic energy implictly, here.
      mass: 8501.3198901104  # = 126.90447 * 1822.888486192 / 27.21138602
      # Coefficients of momentum model in the z direction.
      pz_coeffs:
        - 26824.7
        - -14.2786
        - 0.000193147
        - 6.57577e-007
        - -6.55786e-011
        - -0.0462857
        - 1.99704e-006
      # Coefficients of momentum model in the r direction.
      pr_coeffs:
        - 22.5668
        - -0.00087779
        - 4.24205e-008
        - -2.76085e-012
        - 4.22634e-011
        - -1.98336e-018
      fr: 4561.4  # Lower limit of flight time. Default: 0.
      to: 4726.4  # Upper limit of flight time. Default: .inf.
      x1: 0  # A calibration factor. Default: 0.
      y1: 0  # A calibration factor. Default: 0.
    particle_b:
      # Mass of the model particle. This parameter will be used to
      # calculate kinetic energy from three-dimensional momentum...
      #   (px, py, pz) -> (px**2 + py**2 + pz**2) / 2 / mass.
      # This program does not consider units. You may want to
      # convert the unit of kinetic energy implictly, here.
      mass: 8501.3198901104  # = 126.90447 * 1822.888486192 / 27.21138602
      # Coefficients of momentum model in the z direction.
      pz_coeffs:
        - 40184.2
        - -29.9173
        - 0.000453822
        - 2.81e-006
        - -3.98037e-010
        - -0.0651582
        - 3.60176e-006
      # Coefficients of momentum model in the r direction.
      pr_coeffs:
        - 28.1502
        - -0.000583398
        - 7.7779e-008
        - 7.28141e-012
        - 6.32684e-010
        - -5.92671e-017
      fr: 3221.4  # Lower limit of flight time. Default: 0.
      to: 3373.4  # Upper limit of flight time. Default: .inf.
      x1: 0  # A calibration factor. Default: 0.
      y1: 0  # A calibration factor. Default: 0.